--DROP DATABASE IF EXISTS MYBASE;
--CREATE DATABASE MYBASE;

--ПОСТАВЩИК
DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER
(
ID 	INT,
NAME 	VARCHAR(255),
STATUS	VARCHAR(255),
CITY	VARCHAR(255),
PRIMARY KEY (ID)
--FOREIGN KEY (CITY) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE,
--UNIQUE (CITY)
);

--ПРОДУКТ
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
ID 	INT,
NAME 	VARCHAR(255),
COLOR 	VARCHAR(255),
WEIGHT	INT,
CITY	VARCHAR(255),
PRIMARY KEY (ID)
--FOREIGN KEY (CITY) REFERENCES SUPPLIER ON DELETE CASCADE ON UPDATE CASCADE,
--UNIQUE (CITY)
);

--ALTER TABLE SUPPLIER ADD CONSTRAINT ACITY FOREIGN KEY (CITY) REFERENCES PRODUCT(CITY)  ON DELETE CASCADE ON UPDATE CASCADE;
--ALTER TABLE PRODUCT  ADD CONSTRAINT BCITY FOREIGN KEY (CITY) REFERENCES SUPPLIER(CITY) ON DELETE CASCADE ON UPDATE CASCADE;
--ALTER TABLE SUPPLIER DROP CONSTRAINT BCITY;

INSERT INTO SUPPLIER(ID,NAME,STATUS,CITY) VALUES(1,'ONE','OK','MSK');
INSERT INTO SUPPLIER(ID,NAME,STATUS,CITY) VALUES(2,'TWO','OK','BAX');
INSERT INTO SUPPLIER(ID,NAME,STATUS,CITY) VALUES(3,'THREE','OK','EIE');

INSERT INTO PRODUCT(ID,NAME,COLOR,WEIGHT,CITY) VALUES(1,'ONE','BLUE',13,'MSK');
INSERT INTO PRODUCT(ID,NAME,COLOR,WEIGHT,CITY) VALUES(2,'TWO','BLACK',15,'SPB');
INSERT INTO PRODUCT(ID,NAME,COLOR,WEIGHT,CITY) VALUES(3,'THREE','YELLOW',17,'KGD');

SELECT ID,CITY FROM SUPPLIER
WHERE STATUS = 'OK' AND NAME > 'THREE';

--ПРОЕКТ
-- DROP TABLE IF EXISTS PROJECT;
-- CREATE TABLE PROJECT
-- (
-- ID 	INT,
-- PRIMARY KEY (ID)
-- );
